name: karbonson
version: 1.0.0+1
description: "A new Flutter project."
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.2
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  firebase_messaging: ^15.2.10
  cloud_firestore: ^5.6.12
  firebase_storage: ^12.3.9
  firebase_dynamic_links: ^6.1.10
  flutter_local_notifications: ^19.5.0
  image_picker: ^1.1.2
  shared_preferences: ^2.2.3
  connectivity_plus: ^7.0.0
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.0
  animations: ^2.0.8
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.8
  uuid: ^4.4.0
  app_links: ^3.5.0
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1
  otp: ^3.1.4
  crypto: ^3.0.3
  image: ^4.1.7
  http: ^1.2.2
  local_auth: ^3.0.0
  image_cropper: ^8.0.2
  permission_handler: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  intl: ^0.20.2
  intl_utils: ^2.8.7
  mockito: ^5.5.0
  bloc_test: ^10.0.0
  build_runner: ^2.4.9
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/fonts/
    - assets/avatars/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/karbon2.png"